# devops: hello world

parameters:
  - name: POOL
    displayName: Azure DevOps Agent Pool 
    default: 'AZP-Pool'
    type: string
    values: 
      - 'AZP-Pool'
      - 'AZP-Agent2'

# Set variables
variables:
  path: '/tmp'

resources:
  repositories:
  - repository: hello-devops
    type: github
    endpoint: joehmchiu
    name: joehmchiu/hello-devops
    ref: main

stages:
- stage: Stage1_Checkout_Repo
  displayName: Check out hello-devops repo
  pool: ${{ parameters.POOL }}
  jobs:
    - job: checkout_hello_devops
      displayName: Checkout repo and run ansible playbook
      steps:
        - script: |
            /bin/bash
            dir
            pwd
            echo '$(Agent.BuildDirectory)'
            echo '$(System.DefaultWorkingDirectory)'