# devops: hello world

jobs:
- job: Linux
  pool: AZP-Pool
#    vmImage: 'ubuntu-18.04'
  steps:
  - script: echo "hello world - $(date +'%T %F')!" >> /tmp/foo.log
  - script: |
      dir
      pwd
      echo '$(Agent.BuildDirectory)'
      echo '$(System.DefaultWorkingDirectory)'
  - script: |
      ls -R
      cd './test'
      ansible-playbook -i hosts playbook.yml