- name: test 
  hosts: mac
  vars: 
    run: run.sh
    tmp: /tmp
  tasks: 
  - name: hello world
    debug:
      msg: "Hello World!"
  - name: output hello world
    shell: echo "Hello world! - $(date +'%T %F')" >> /tmp/foo.log
  - name: copy script to mac
    copy:
      src: "{{root}}/{{run}}"
      dest: "{{tmp}}/{{run}}"
      mode: '0755'
  - name: build mongo api image and deploy to the kubernetes cluster
    shell: "{{tmp}}/{{run}}"
